language: node_js
node_js:
- "5"
- "4"
env:
  - WEBPACK_CONFIG=webpack.config.babel-to-ts.js
  - WEBPACK_CONFIG=webpack.config.js
install:
- npm install typescript@next -g
- npm install typings -g
- npm install webpack -g
- npm install
- npm link typescript
- typings install
script:
- tsc
- webpack --config $WEBPACK_CONFIG
- node bundle.js
cache:
  directories:
  - node_modules
  - typings
